In [1]:
!pip install multilingual-clip

Requirement already satisfied: multilingual-clip in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (1.0.10)
Requirement already satisfied: transformers in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from multilingual-clip) (4.28.0)
Requirement already satisfied: filelock in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (0.26.1)
Requirement already satisfied: numpy>=1.17 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (2024.9.11)
Requirement already satisfied: requests in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (2.32.3)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from transformers->multilingual-clip) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers->multilingual-clip) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers->multilingual-clip) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from requests->transformers->multilingual-clip) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from requests->transformers->multilingual-clip) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from requests->transformers->multilingual-clip) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages (from requests->transformers->multilingual-clip) (2024.8.30)

In [63]:
import matplotlib.image as mpimg
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import json
import torch
from collections import Counter
from PIL import Image
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import clip
#from google.colab import drive
import os
from os import listdir
from os.path import isfile, join
import matplotlib.image as mpimg
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import json
import torch
from collections import Counter
from PIL import Image
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import clip
#from google.colab import drive
import os
from os import listdir
from os.path import isfile, join

In [64]:
def find_most_common_answer(answers):
    answer_counter = Counter(answers)
    most_common_answers = answer_counter.most_common()
    most_common_answer, count = most_common_answers[0]
    return most_common_answer

def select_most_common_answers(df):
    selected_answers = []
    for idx, row in df.iterrows():
        answers = [answer["answer"] for answer in row["answers"]]
        selected_answer = find_most_common_answer(answers)

        selected_answers.append({"answer": selected_answer
        })

    # Update the "answer" and "answer_confidence" columns in the DataFrame
    df[["answer"]] = pd.DataFrame(selected_answers)

    return df.drop(["answers"], axis=1)

def plot_loss(train_loss, val_loss):
    epochs = range(1, len(train_loss) + 1)

    plt.plot(epochs, train_loss, label='Training Loss')
    plt.plot(epochs, val_loss, label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.title('Training and Validation Loss')
    plt.legend()
    plt.show()

def plot_img(path):
    # Load the JPEG image
    image = mpimg.imread(path)

    # Plot the image
    plt.imshow(image)
    plt.axis('off')  # Remove axis ticks and labels
    plt.show()

In [65]:
def dataloader_json(path,test=False):
    # Load the JSON file
    with open(path, 'r') as f:
        data = json.load(f)
    # Create a DataFrame from the loaded JSON data
    df = pd.DataFrame(data)

    if test:
        return df

    return select_most_common_answers(df)

In [66]:
train_df = dataloader_json("Annotations/Annotations/train_beng.json")

train_df

,image,question,answer_type,answerable,answer
0,VizWiz_train_00000000.jpg,এই পণ্যের নাম কি?,other,1,বেসিল পাতা
1,VizWiz_train_00000001.jpg,তুমি কি বলতে পারবে এর মধ্যে কি আছে দয়া করে?,other,1,কোকো
2,VizWiz_train_00000002.jpg,এটা কি সস নাকি টমেটো? ধন্যবাদ.,other,1,টমেটো
3,VizWiz_train_00000003.jpg,এই ছবিতে ক্যাপচা কি?,other,1,ছাকন
4,VizWiz_train_00000004.jpg,এসব কি?,other,1,সৌরজগত্‍
...,...,...,...,...,...
20518,VizWiz_train_00023949.jpg,ল্যাপটপের রং কি?,other,1,কালো
20519,VizWiz_train_00023950.jpg,"তুমি এটা দেখতে পাচ্ছ? যদি তাই হয়, তাহলে বলো এ...",other,1,অ‌ধাতু
20520,VizWiz_train_00023951.jpg,আমাকে তিনটা সংখ্যা লিখতে হবে কেন?,unanswerable,0,প্রযোজ্য নয় এমন ছবি
20521,VizWiz_train_00023952.jpg,এটা কি বক্স?,yes/no,1,না
20522,VizWiz_train_00023953.jpg,এই ছবিতে কি আছে?,other,1,গাড়ি

In [67]:
train_df['answer'].value_counts()

answer
অ‌ধাতু                         3904
প্রযোজ্য নয়                   3022
না                              569
হ্যাঁ                           519
সাদা                            296
                               ...
আকার পরিবর্তন                     1
জালপেনো অংশগুলির পূর্বদৃশ্য       1
মিনিট ৩০ সেকেন্ড                  1
রাস্পবেরি শাওয়ারেজ               1
নতুন ippui                        1
Name: count, Length: 4899, dtype: int64

In [68]:
val_df = dataloader_json("Annotations/Annotations/val_beng.json")
val_df

,image,question,answer_type,answerable,answer
0,VizWiz_val_00000000.jpg,"ঠিক আছে। অন্য একটি ছবি আছে, আশা করি এটাই ভালো ...",unanswerable,0,অ‌ধাতু
1,VizWiz_val_00000001.jpg,আপনি কি আমাকে বলবেন এই ওষুধটা কিসের?,other,1,রাতের সময়
2,VizWiz_val_00000002.jpg,এই বইয়ের শিরোনাম কী?,other,1,বছর
3,VizWiz_val_00000003.jpg,নীলটা কোনটা?,other,1,ডানদিকে
4,VizWiz_val_00000004.jpg,তীর কি বলে?,unanswerable,0,অ‌ধাতু
...,...,...,...,...,...
4314,VizWiz_val_00004314.jpg,এটা কি?,other,1,সালাদের পোশাক
4315,VizWiz_val_00004315.jpg,এটা কি আধুনিক?,unanswerable,0,প্রযোজ্য নয়
4316,VizWiz_val_00004316.jpg,"আমি এই ব্যাটারিটা কিনব, তুমি কি মডেল আর নাম দে...",unanswerable,0,অ‌ধাতু
4317,VizWiz_val_00004317.jpg,এটা কি ধরনের মিশ্রণ?,other,1,কেক
4318,VizWiz_val_00004318.jpg,এটা কি ধরনের মসলা?,other,1,আগর

In [69]:
data_df = pd.concat((train_df,val_df), axis =0,ignore_index=True)
data_df

,image,question,answer_type,answerable,answer
0,VizWiz_train_00000000.jpg,এই পণ্যের নাম কি?,other,1,বেসিল পাতা
1,VizWiz_train_00000001.jpg,তুমি কি বলতে পারবে এর মধ্যে কি আছে দয়া করে?,other,1,কোকো
2,VizWiz_train_00000002.jpg,এটা কি সস নাকি টমেটো? ধন্যবাদ.,other,1,টমেটো
3,VizWiz_train_00000003.jpg,এই ছবিতে ক্যাপচা কি?,other,1,ছাকন
4,VizWiz_train_00000004.jpg,এসব কি?,other,1,সৌরজগত্‍
...,...,...,...,...,...
24837,VizWiz_val_00004314.jpg,এটা কি?,other,1,সালাদের পোশাক
24838,VizWiz_val_00004315.jpg,এটা কি আধুনিক?,unanswerable,0,প্রযোজ্য নয়
24839,VizWiz_val_00004316.jpg,"আমি এই ব্যাটারিটা কিনব, তুমি কি মডেল আর নাম দে...",unanswerable,0,অ‌ধাতু
24840,VizWiz_val_00004317.jpg,এটা কি ধরনের মিশ্রণ?,other,1,কেক
24841,VizWiz_val_00004318.jpg,এটা কি ধরনের মসলা?,other,1,আগর

In [70]:
ans_lb = LabelEncoder()
data_df['answer'] = ans_lb.fit_transform(data_df['answer'])
ans_type_lb = LabelEncoder()
data_df['answer_type']= ans_type_lb.fit_transform(data_df['answer_type'])

In [71]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [72]:
from multilingual_clip import pt_multilingual_clip
import transformers

model_name = 'M-CLIP/XLM-Roberta-Large-Vit-L-14'

# Load Model & Tokenizer
model = pt_multilingual_clip.MultilingualCLIP.from_pretrained(model_name)
tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)

#embeddings = model.forward(texts, tokenizer)
#print(embeddings.shape)

/home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/arif/anaconda3/envs/env_ratnabali/lib/python3.9/site-packages/transformers/modeling_utils.py:442: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location="cpu")
Some weights of the model checkpoint at xlm-roberta-large were not used when initializing XLMRobertaModel: ['lm_head.dense.bias', 'lm_head.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [73]:
import torch
model_clip, preprocess = clip.load("ViT-L/14", device=device)

from torchvision import transforms
# Prepare the image
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
#model_clip.context_length=512
encodings = []
for img , question in tqdm(zip(data_df['image'],data_df['question'])):
    if "train" in img:
        image = preprocess(Image.open(f'train/{img}')).unsqueeze(0).to(device)
    elif "test" in img:
       image = preprocess(Image.open(f'test/{img}')).unsqueeze(0).to(device)
    else:
        image = preprocess(Image.open(f'val/{img}')).unsqueeze(0).to(device)

    text = tokenizer(question, return_tensors="pt", padding=True, truncation=True).to(device)
    with torch.no_grad():
        image_encoding = model_clip.encode_image(image)
        text_encoding = model.forward(question, tokenizer).to(device)
        #print(text_encoding.shape)
        encodings.append(torch.cat([image_encoding, text_encoding], dim=-1))

5it [00:00, 21.15it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

8it [00:00, 20.32it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

14it [00:00, 20.06it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

17it [00:00, 20.30it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

23it [00:01, 22.24it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

29it [00:01, 23.38it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

32it [00:01, 23.93it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

38it [00:01, 22.37it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

44it [00:02, 23.22it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

47it [00:02, 23.59it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

53it [00:02, 23.83it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

59it [00:02, 23.38it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

62it [00:02, 22.12it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

68it [00:03, 23.01it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

73it [00:03, 22.27it/s]

torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

KeyboardInterrupt:

In [41]:
torch.save(encodings,"model-ml.pt")

In [61]:
encodings

[tensor([[0.0085, 1.1250, 0.0895,  ..., 0.1511, 0.2544, 0.4331]],
        device='cuda:0'),
 tensor([[ 0.1897,  0.3145,  0.0903,  ...,  0.0042,  0.2063, -0.0134]],
        device='cuda:0'),
 tensor([[ 0.6279, -0.0081, -0.1984,  ..., -0.3382,  0.3426, -0.1012]],
        device='cuda:0'),
 tensor([[0.4348, 0.6797, 0.3953,  ..., 0.0102, 0.2194, 0.1637]],
        device='cuda:0'),
 tensor([[ 1.0811,  0.6187, -0.0789,  ..., -0.0274,  0.0387, -0.1133]],
        device='cuda:0'),
 tensor([[-0.1033,  1.1816,  0.1733,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.5464,  0.8525,  0.0166,  ...,  0.0696,  0.5660,  0.6703]],
        device='cuda:0'),
 tensor([[ 0.0735,  0.9424, -0.2874,  ...,  0.3132,  0.3494, -0.3200]],
        device='cuda:0'),
 tensor([[ 0.0836,  0.5137,  0.0739,  ..., -0.1577,  0.4445, -0.1183]],
        device='cuda:0'),
 tensor([[-0.4580,  0.7593,  0.1772,  ..., -0.1968,  0.1190, -0.0096]],
        device='cuda:0'),
 tensor([[ 0.5298,  0.5601, -0.2147,  ..., -0.0326,  0.0237, -0.1349]],
        device='cuda:0'),
 tensor([[ 0.5947, -0.0154,  0.4744,  ..., -0.0313,  0.3322,  0.0582]],
        device='cuda:0'),
 tensor([[ 0.7925,  0.3843, -0.6807,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.1394,  0.2869,  0.4792,  ...,  0.2701,  0.0323, -0.1300]],
        device='cuda:0'),
 tensor([[-0.0168,  0.5659,  0.2483,  ..., -0.0453, -0.0148, -0.0986]],
        device='cuda:0'),
 tensor([[0.4585, 0.7471, 0.4097,  ..., 0.0244, 0.3326, 0.0321]],
        device='cuda:0'),
 tensor([[ 0.3042,  0.1525, -0.6045,  ..., -0.0338,  0.3623,  0.1028]],
        device='cuda:0'),
 tensor([[-0.0021, -0.6343,  0.2930,  ...,  0.0957,  0.2153,  0.2530]],
        device='cuda:0'),
 tensor([[ 0.9009,  0.0237, -0.3848,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.1370,  0.3821, -0.0118,  ...,  0.0134,  0.1434, -0.0649]],
        device='cuda:0'),
 tensor([[ 0.8164,  0.0561, -0.8950,  ...,  0.3046, -0.0015,  0.0186]],
        device='cuda:0'),
 tensor([[ 0.7671,  0.7925, -0.1288,  ...,  0.2106,  0.5784,  0.6781]],
        device='cuda:0'),
 tensor([[ 0.7388,  0.6904, -0.1276,  ...,  0.0183, -0.0181, -0.0364]],
        device='cuda:0'),
 tensor([[-0.0984,  0.1268, -0.1058,  ...,  0.1244,  0.0415, -0.0753]],
        device='cuda:0'),
 tensor([[-0.1855,  0.5542, -0.2307,  ...,  0.2155, -0.3155, -0.0686]],
        device='cuda:0'),
 tensor([[ 0.3105,  0.5356, -0.6030,  ...,  0.0692,  0.2324, -0.1262]],
        device='cuda:0'),
 tensor([[ 1.0498,  0.5034, -0.1729,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.0889,  0.3628,  0.2688,  ...,  0.0809,  0.4148,  0.0616]],
        device='cuda:0'),
 tensor([[ 0.4033,  0.1667,  0.0773,  ..., -0.0440,  0.0768, -0.1407]],
        device='cuda:0'),
 tensor([[-0.1191,  0.7969,  0.1327,  ..., -0.0286,  0.0617, -0.0036]],
        device='cuda:0'),
 tensor([[ 0.0352,  0.7617,  0.0447,  ..., -0.0403,  0.0356, -0.1272]],
        device='cuda:0'),
 tensor([[ 0.2057, -0.1443, -0.2249,  ...,  0.3446,  0.0688,  0.3580]],
        device='cuda:0'),
 tensor([[ 0.3455,  0.6548, -0.0266,  ..., -0.1295,  0.2151, -0.2215]],
        device='cuda:0'),
 tensor([[0.0658, 0.9126, 0.2410,  ..., 0.0626, 0.7709, 0.8751]],
        device='cuda:0'),
 tensor([[ 1.3096e+00, -1.5698e-01,  3.0005e-01,  ..., -5.8254e-02,
           1.0862e-03, -1.3800e-01]], device='cuda:0'),
 tensor([[ 0.2476,  0.8618, -0.4280,  ..., -0.0881,  0.0374, -0.0229]],
        device='cuda:0'),
 tensor([[ 0.3394,  0.6606, -0.5122,  ...,  0.0198,  0.4851, -0.0688]],
        device='cuda:0'),
 tensor([[ 0.8413, -0.2632,  0.5977,  ..., -0.0589,  0.2502,  0.4632]],
        device='cuda:0'),
 tensor([[0.6816, 0.8306, 0.0158,  ..., 0.1803, 0.1186, 0.4557]],
        device='cuda:0'),
 tensor([[ 0.7925,  0.9819,  0.4341,  ...,  0.0149, -0.0107, -0.2226]],
        device='cuda:0'),
 tensor([[-0.4585,  0.8218,  0.2625,  ...,  0.4077, -0.1475,  0.4723]],
        device='cuda:0'),
 tensor([[-0.1199,  0.0623,  0.5166,  ...,  0.0222,  0.2916, -0.2741]],
        device='cuda:0'),
 tensor([[-0.1609,  1.1133,  0.4199,  ..., -0.0267,  0.0853, -0.1961]],
        device='cuda:0'),
 tensor([[-0.1497, -0.1321, -0.0876,  ...,  0.0934,  0.2139,  0.1436]],
        device='cuda:0'),
 tensor([[ 0.4634, -0.0067, -0.5610,  ...,  0.0260,  0.1294, -0.2117]],
        device='cuda:0'),
 tensor([[ 0.4226,  1.3154,  0.7153,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 1.0068,  0.4578,  0.2150,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.2778,  0.3982,  0.7241,  ...,  0.1911,  0.1594,  0.4926]],
        device='cuda:0'),
 tensor([[-0.4722,  0.2069,  0.7446,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.2559,  0.4351,  0.1824,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.9741, -0.2018, -0.0310,  ...,  0.0072,  0.1097, -0.0427]],
        device='cuda:0'),
 tensor([[ 0.6909,  0.4607,  0.6523,  ..., -0.1772, -0.1327,  0.2885]],
        device='cuda:0'),
 tensor([[ 0.2417, -0.0742,  0.1019,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.1727,  0.3364, -0.0091,  ...,  0.1243,  0.0352, -0.0101]],
        device='cuda:0'),
 tensor([[ 0.3181,  0.0277, -0.0540,  ..., -0.0534,  0.4494, -0.4101]],
        device='cuda:0'),
 tensor([[ 0.6016,  0.0947, -0.1862,  ...,  0.1582,  0.3061, -0.0632]],
        device='cuda:0'),
 tensor([[ 0.3430,  0.0336, -0.2791,  ..., -0.4820,  0.3133,  0.3263]],
        device='cuda:0'),
 tensor([[ 0.1583,  0.0738, -0.1171,  ..., -0.1489, -0.0124, -0.0070]],
        device='cuda:0'),
 tensor([[1.2725, 0.6616, 0.5098,  ..., 0.1179, 0.5334, 0.5833]],
        device='cuda:0'),
 tensor([[-0.6685,  0.1566,  0.1827,  ...,  0.0692,  0.2324, -0.1262]],
        device='cuda:0'),
 tensor([[ 0.4001,  0.1790,  0.7061,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.2247,  0.4790, -0.1923,  ..., -0.2286,  0.2793,  0.0942]],
        device='cuda:0'),
 tensor([[ 0.1442,  0.2295, -0.5928,  ...,  0.0655,  0.1251, -0.2661]],
        device='cuda:0'),
 tensor([[-0.4448,  0.6772,  0.5254,  ..., -0.1128,  0.3060,  0.0718]],
        device='cuda:0'),
 tensor([[ 0.4849, -0.0244, -0.1671,  ...,  0.0821,  0.0435, -0.1268]],
        device='cuda:0'),
 tensor([[ 1.2998,  0.4609,  0.0478,  ..., -0.0161,  0.0850, -0.0384]],
        device='cuda:0'),
 tensor([[ 0.5635,  1.2471,  0.7446,  ...,  0.4756, -0.0150,  0.0767]],
        device='cuda:0'),
 tensor([[ 0.0650, -0.0223,  0.2222,  ..., -0.3105,  0.2117,  0.1142]],
        device='cuda:0'),
 tensor([[-0.0096,  0.4604, -0.0420,  ..., -0.1478,  0.0820, -0.0610]],
        device='cuda:0'),
 tensor([[ 0.7290,  0.4692,  0.1324,  ...,  0.0301,  0.0838, -0.1404]],
        device='cuda:0'),
 tensor([[ 0.2048,  0.9307, -0.1122,  ..., -0.1393, -0.0299,  0.5057]],
        device='cuda:0'),
 tensor([[ 0.5459,  0.6294,  0.2085,  ..., -0.0502, -0.0522, -0.0385]],
        device='cuda:0'),
 tensor([[-0.0104, -0.1389,  0.2245,  ...,  0.3112,  0.0123,  0.1420]],
        device='cuda:0'),
 tensor([[ 0.5083,  0.7720,  0.4490,  ...,  0.0272,  0.2361, -0.0820]],
        device='cuda:0'),
 tensor([[ 0.1459,  0.9927,  0.1042,  ..., -0.0089,  0.4546,  0.2313]],
        device='cuda:0'),
 tensor([[ 0.8350,  0.1299,  0.0734,  ..., -0.0599,  0.4670, -0.2735]],
        device='cuda:0'),
 tensor([[-0.3757,  0.2627,  0.4001,  ...,  0.0045,  0.1055,  0.4190]],
        device='cuda:0'),
 tensor([[ 0.1436, -0.4453,  0.5815,  ...,  0.2701,  0.0323, -0.1300]],
        device='cuda:0'),
 tensor([[-0.9028, -0.2527,  0.3569,  ..., -0.0981,  0.1027, -0.2024]],
        device='cuda:0'),
 tensor([[ 0.2435,  0.4539, -0.4360,  ..., -0.1803,  0.1874,  0.1003]],
        device='cuda:0'),
 tensor([[ 0.0560, -0.0288,  0.3838,  ..., -0.0637,  0.1344, -0.3827]],
        device='cuda:0'),
 tensor([[ 0.3440,  0.4658, -0.0032,  ...,  0.0114,  0.1803, -0.1139]],
        device='cuda:0'),
 tensor([[-2.1313e-01,  3.6938e-01,  2.5659e-01,  ..., -2.1462e-04,
           3.3195e-01,  2.3086e-01]], device='cuda:0'),
 tensor([[ 0.0932,  0.3936,  0.3904,  ...,  0.1389, -0.1275, -0.1155]],
        device='cuda:0'),
 tensor([[-0.2646,  0.4885, -0.1742,  ...,  0.1301,  0.2061,  0.1833]],
        device='cuda:0'),
 tensor([[ 0.7290, -0.1880, -0.5000,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.4392,  0.2605, -0.0809,  ..., -0.2468,  0.5913, -0.3896]],
        device='cuda:0'),
 tensor([[ 0.3352,  1.2285,  0.3635,  ..., -0.0757,  0.1655, -0.3223]],
        device='cuda:0'),
 tensor([[ 0.1736, -0.2534, -0.0439,  ...,  0.3472, -0.1277, -0.1768]],
        device='cuda:0'),
 tensor([[ 0.0945,  1.0234,  0.2467,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.0225,  0.8110, -0.1080,  ..., -0.3335,  0.2592,  0.4150]],
        device='cuda:0'),
 tensor([[ 0.1830,  1.0537,  0.5254,  ...,  0.2719,  0.3283, -0.0070]],
        device='cuda:0'),
 tensor([[ 0.3303,  0.5947, -0.4680,  ...,  0.0797,  0.1928, -0.2603]],
        device='cuda:0'),
 tensor([[-0.3970,  0.1138, -0.8701,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.6494,  0.8296, -0.0328,  ...,  0.0521,  0.5777,  0.3770]],
        device='cuda:0'),
 tensor([[ 0.5522,  0.5366, -0.2664,  ...,  0.1764,  0.7435,  0.4010]],
        device='cuda:0'),
 tensor([[ 0.4885,  0.6167, -0.0334,  ...,  0.0260,  0.1294, -0.2117]],
        device='cuda:0'),
 tensor([[-0.4097, -0.3857,  0.4358,  ..., -0.0142,  0.2086, -0.2242]],
        device='cuda:0'),
 tensor([[ 0.7476,  0.6143,  0.2773,  ...,  0.1613, -0.1210, -0.0661]],
        device='cuda:0'),
 tensor([[ 0.0868,  0.5005,  0.1766,  ...,  0.0179,  0.2784, -0.0450]],
        device='cuda:0'),
 tensor([[ 0.4224,  0.2617,  0.4658,  ...,  0.0383,  0.1429, -0.2005]],
        device='cuda:0'),
 tensor([[-0.6172, -0.0063,  0.1375,  ...,  0.4552, -0.0045, -0.2008]],
        device='cuda:0'),
 tensor([[ 0.3020,  0.1627,  0.0842,  ..., -0.3295, -0.3333, -0.4128]],
        device='cuda:0'),
 tensor([[ 0.5303,  0.2305,  0.0611,  ..., -0.0226,  0.4637,  0.0558]],
        device='cuda:0'),
 tensor([[ 0.7417,  0.3318,  0.1470,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.0618,  0.3477, -0.0925,  ..., -0.0088,  0.0605, -0.1348]],
        device='cuda:0'),
 tensor([[ 0.4331,  0.4949,  0.3035,  ..., -0.1437,  0.5273, -0.3611]],
        device='cuda:0'),
 tensor([[-0.5864,  0.5708,  0.6621,  ..., -0.1559,  0.2889, -0.3147]],
        device='cuda:0'),
 tensor([[-0.1350,  0.1370,  0.2075,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.4934,  0.0880, -0.2307,  ..., -0.1397,  0.0650, -0.1721]],
        device='cuda:0'),
 tensor([[-0.0763,  0.8242,  0.0301,  ...,  0.1123,  0.2228, -0.1768]],
        device='cuda:0'),
 tensor([[-0.6162,  0.4126,  0.3569,  ...,  0.0372,  0.7162,  0.8570]],
        device='cuda:0'),
 tensor([[ 0.0490,  0.7427, -0.4600,  ..., -0.0238,  0.1475, -0.0687]],
        device='cuda:0'),
 tensor([[ 0.3738,  0.8804,  0.0912,  ..., -0.0371,  0.1187, -0.0892]],
        device='cuda:0'),
 tensor([[ 0.6616,  0.3625, -0.1152,  ...,  0.2279, -0.3339,  0.1497]],
        device='cuda:0'),
 tensor([[-0.2969, -0.2537, -0.5718,  ...,  0.0328,  0.1509,  0.2563]],
        device='cuda:0'),
 tensor([[ 0.3337, -0.0241,  0.2157,  ...,  0.4203,  0.5201, -0.0130]],
        device='cuda:0'),
 tensor([[ 0.3496,  0.3899,  0.0266,  ..., -0.0371,  0.1187, -0.0892]],
        device='cuda:0'),
 tensor([[ 0.1849,  0.5513, -0.3186,  ...,  0.1934, -0.1567, -0.0531]],
        device='cuda:0'),
 tensor([[ 0.3643,  0.2683, -0.0441,  ..., -0.0499,  0.0285,  0.1731]],
        device='cuda:0'),
 tensor([[ 0.0493,  0.0316, -0.7461,  ...,  0.1065,  0.2444,  0.1376]],
        device='cuda:0'),
 tensor([[ 0.1995,  0.7461,  0.5200,  ...,  0.0144,  0.2260, -0.2036]],
        device='cuda:0'),
 tensor([[-0.0453,  1.2012,  0.4956,  ..., -0.1897,  0.5237, -0.3762]],
        device='cuda:0'),
 tensor([[ 0.2612,  0.1583, -0.0585,  ..., -0.0440,  0.0768, -0.1407]],
        device='cuda:0'),
 tensor([[ 0.7539,  0.7314, -0.1217,  ...,  0.0696,  0.5660,  0.6703]],
        device='cuda:0'),
 tensor([[ 0.5522,  1.1162, -0.1647,  ...,  0.0205, -0.1515,  0.2182]],
        device='cuda:0'),
 tensor([[ 0.1503,  0.5522,  0.3074,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.3601,  0.1422,  0.3350,  ..., -0.1897,  0.5237, -0.3762]],
        device='cuda:0'),
 tensor([[-0.0923,  0.9902, -0.0776,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.2147,  0.6553,  0.0985,  ..., -0.4723,  0.4871, -0.4092]],
        device='cuda:0'),
 tensor([[-0.1102,  1.0059, -0.1420,  ..., -0.0274,  0.0387, -0.1133]],
        device='cuda:0'),
 tensor([[ 0.0019, -0.5771, -0.0067,  ...,  0.0407,  0.3383, -0.1518]],
        device='cuda:0'),
 tensor([[ 0.2333,  0.3506, -0.1873,  ..., -0.1820,  0.1687,  0.3308]],
        device='cuda:0'),
 tensor([[-0.3867,  0.0770,  0.0317,  ...,  0.2374, -0.1436, -0.4989]],
        device='cuda:0'),
 tensor([[ 0.4939,  0.3301,  0.6460,  ...,  0.0692,  0.2324, -0.1262]],
        device='cuda:0'),
 tensor([[-0.0645,  0.5391, -0.2520,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.0928, -0.2842,  0.1969,  ...,  0.0183, -0.0181, -0.0364]],
        device='cuda:0'),
 tensor([[ 0.5571,  0.3596, -0.2625,  ...,  0.4586, -0.0430,  0.0267]],
        device='cuda:0'),
 tensor([[0.4517, 0.1656, 0.1614,  ..., 0.1952, 0.1665, 0.4273]],
        device='cuda:0'),
 tensor([[ 0.0053,  0.5996,  0.3018,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.3706,  0.1744, -0.2871,  ...,  0.4016,  0.0354,  0.2330]],
        device='cuda:0'),
 tensor([[ 0.4167, -0.1107,  0.3083,  ...,  0.0561,  0.1884, -0.1644]],
        device='cuda:0'),
 tensor([[ 0.6650,  1.1709, -0.0468,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.5454,  0.6436,  0.2502,  ...,  0.2192, -0.2288,  0.1160]],
        device='cuda:0'),
 tensor([[ 0.0674,  1.2939,  0.0418,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.7524,  1.0996, -0.2089,  ..., -0.1121, -0.0959, -0.3703]],
        device='cuda:0'),
 tensor([[ 0.1627,  0.1735, -0.2129,  ...,  0.1553, -0.1095, -0.0330]],
        device='cuda:0'),
 tensor([[ 0.1707,  1.1680,  0.0250,  ..., -0.1041,  0.5125, -0.3315]],
        device='cuda:0'),
 tensor([[ 0.5518,  0.1720, -0.5767,  ..., -0.0581,  0.0365, -0.2810]],
        device='cuda:0'),
 tensor([[ 0.1899, -0.6929, -0.9102,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.1980,  0.1523,  0.1434,  ..., -0.0145,  0.2734, -0.0547]],
        device='cuda:0'),
 tensor([[-0.4575,  0.6475,  0.0215,  ...,  0.0137, -0.2165,  0.1474]],
        device='cuda:0'),
 tensor([[0.5708, 0.8413, 0.3755,  ..., 0.0521, 0.5777, 0.3770]],
        device='cuda:0'),
 tensor([[-0.1421,  0.1755,  0.5176,  ...,  0.0912,  0.1609,  0.3409]],
        device='cuda:0'),
 tensor([[0.4377, 0.1819, 0.1471,  ..., 0.0900, 0.5993, 0.3002]],
        device='cuda:0'),
 tensor([[ 0.5576,  0.6255,  0.1658,  ..., -0.0471,  0.0513, -0.1044]],
        device='cuda:0'),
 tensor([[ 0.1498,  0.9277,  0.0307,  ...,  0.2379, -0.0802,  0.1215]],
        device='cuda:0'),
 tensor([[ 0.7827,  0.0724, -0.2761,  ...,  0.0693,  0.4972,  0.1622]],
        device='cuda:0'),
 tensor([[0.4468, 1.3135, 0.6567,  ..., 0.1397, 0.6921, 1.0308]],
        device='cuda:0'),
 tensor([[ 0.0110,  0.8120,  0.3962,  ...,  0.0135, -0.2855, -0.2824]],
        device='cuda:0'),
 tensor([[ 0.6743,  0.7568, -0.3193,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.2112, -0.0562,  0.2747,  ..., -0.0065, -0.0124, -0.1397]],
        device='cuda:0'),
 tensor([[ 0.5332,  0.2039, -0.1807,  ...,  0.1344, -0.3173, -0.1247]],
        device='cuda:0'),
 tensor([[ 0.5239,  1.2246,  0.2277,  ...,  0.0465,  0.0880, -0.0235]],
        device='cuda:0'),
 tensor([[ 0.3394,  0.7168,  0.3547,  ...,  0.4261,  0.4838, -0.1144]],
        device='cuda:0'),
 tensor([[ 0.3252,  0.3774,  0.2651,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.0071,  0.5327,  0.3201,  ...,  0.1572,  0.1077, -0.0862]],
        device='cuda:0'),
 tensor([[ 0.7729,  0.7529,  0.1453,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.2488,  0.8174,  0.2126,  ..., -0.1381,  0.7024, -0.4687]],
        device='cuda:0'),
 tensor([[ 0.6987, -0.0663, -0.0075,  ..., -0.0626,  0.1281, -0.1022]],
        device='cuda:0'),
 tensor([[ 0.2732,  0.0163,  0.2986,  ...,  0.0477,  0.1974, -0.0232]],
        device='cuda:0'),
 tensor([[-0.0411,  0.5474, -0.6050,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.0410,  0.1881,  0.1161,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[0.5254, 0.7632, 1.0059,  ..., 0.0109, 0.0562, 0.2255]],
        device='cuda:0'),
 tensor([[-0.9058,  0.3740, -0.2197,  ..., -0.0371,  0.1187, -0.0892]],
        device='cuda:0'),
 tensor([[ 0.0986,  0.4370, -0.0062,  ...,  0.0036, -0.0966, -0.0797]],
        device='cuda:0'),
 tensor([[-0.0603,  0.4705,  0.4656,  ...,  0.2814,  0.2763, -0.0184]],
        device='cuda:0'),
 tensor([[ 0.8350,  1.1455, -0.3550,  ..., -0.0274,  0.0387, -0.1133]],
        device='cuda:0'),
 tensor([[-0.0456,  1.2930, -0.1851,  ...,  0.0303,  0.1608, -0.0225]],
        device='cuda:0'),
 tensor([[-0.0523,  0.7812,  0.3772,  ...,  0.0121,  0.1304,  0.0706]],
        device='cuda:0'),
 tensor([[-0.0836,  0.9443,  0.1082,  ..., -0.0232, -0.1199, -0.1224]],
        device='cuda:0'),
 tensor([[ 0.4077, -0.0693, -0.0166,  ..., -0.0920,  0.2870, -0.1935]],
        device='cuda:0'),
 tensor([[ 0.0821,  0.2059,  0.2334,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.3647,  0.6997,  0.1110,  ..., -0.2237,  0.7059, -0.1267]],
        device='cuda:0'),
 tensor([[-0.2791, -0.1379, -0.1165,  ..., -0.0122, -0.0330, -0.1096]],
        device='cuda:0'),
 tensor([[0.1801, 0.3354, 0.2473,  ..., 0.0479, 0.3094, 0.0393]],
        device='cuda:0'),
 tensor([[ 0.1746,  0.1863,  0.2023,  ...,  0.0868,  0.0680, -0.0562]],
        device='cuda:0'),
 tensor([[ 0.0942,  0.3225,  0.0307,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.3301,  0.6079, -0.2211,  ..., -0.0149,  0.1411, -0.1684]],
        device='cuda:0'),
 tensor([[ 0.8447,  0.5430, -0.0233,  ..., -0.1099, -0.1638, -0.0569]],
        device='cuda:0'),
 tensor([[ 0.2207,  1.3740, -0.2791,  ..., -0.0203,  0.0351, -0.1349]],
        device='cuda:0'),
 tensor([[ 0.8545,  0.0978, -0.4634,  ..., -0.0390,  0.0751, -0.1659]],
        device='cuda:0'),
 tensor([[-0.0605, -0.0986, -0.0469,  ...,  0.4256,  0.2239,  0.2176]],
        device='cuda:0'),
 tensor([[ 1.2930,  0.6064,  0.4373,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 1.4805,  0.6025,  0.5264,  ...,  0.0183, -0.0181, -0.0364]],
        device='cuda:0'),
 tensor([[ 0.0651,  0.3699, -0.0538,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 0.4214,  0.2004, -0.3018,  ..., -0.0965, -0.1078,  0.3894]],
        device='cuda:0'),
 tensor([[ 1.1787,  0.6338,  0.1460,  ...,  0.1011,  0.1915, -0.2481]],
        device='cuda:0'),
 tensor([[-0.1473,  0.9336,  0.0180,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[ 1.1621,  0.0414,  0.0604,  ...,  0.1489, -0.0863,  0.0390]],
        device='cuda:0'),
 tensor([[ 0.5562,  0.0249,  0.2791,  ..., -0.0281,  0.0918, -0.1423]],
        device='cuda:0'),
 tensor([[-0.3848,  0.4934, -0.4873,  ..., -0.2553, -0.4065, -0.1792]],
        device='cuda:0'),
 tensor([[ 0.5137,  1.0137,  0.1638,  ...,  0.0886,  0.1434, -0.1157]],
        device='cuda:0'),
 tensor([[ 0.7158,  0.7852, -0.7539,  ..., -0.1936,  0.5888,  0.1142]],
        device='cuda:0'),

In [42]:
print(len(data_df))

24842

In [43]:
# Generate the indices for train-test split
indices = np.arange(len(data_df))

# Perform train-test split
train_indices, test_indices = train_test_split(indices, test_size=0.05, random_state=42)

In [44]:
train = data_df.iloc[train_indices] 
train = train.reset_index(drop=True)
train

,image,question,answer_type,answerable,answer
0,VizWiz_train_00017501.jpg,এর ভেতরে কি আছে?,2,0,349
1,VizWiz_val_00003817.jpg,এই সিসিটিভির ক্রমিক সংখ্যা কি?,2,0,349
2,VizWiz_train_00002858.jpg,শার্টটা কিসের?,1,1,3541
3,VizWiz_train_00004344.jpg,আমি কি দেখছি?,1,1,4229
4,VizWiz_train_00014612.jpg,আপনি কি দয়া করে আমাকে বলবেন যে এটা টিভি স্ট্য...,3,1,5120
...,...,...,...,...,...
23594,VizWiz_val_00001052.jpg,এটা কি বলে? এটা কি বলে?,2,0,3026
23595,VizWiz_train_00005390.jpg,এটা কি ধরনের সোডা?,1,1,2841
23596,VizWiz_train_00000860.jpg,বালম বি-এল-এম কি এই কন্টেইনার সম্পর্কে লিখেছে?,3,1,2514
23597,VizWiz_train_00015795.jpg,শার্টটা কি বলে?,1,1,428
23598,VizWiz_val_00003131.jpg,শার্টটা কিসের?,1,1,3910

In [45]:
test = data_df.iloc[test_indices]
test = test.reset_index(drop=True)
test

,image,question,answer_type,answerable,answer
0,VizWiz_train_00005163.jpg,এটা কি আলো নাকি অন্ধকার?,1,1,1502
1,VizWiz_train_00004569.jpg,থার্মোস্তা কি বলে?,2,0,3025
2,VizWiz_train_00023795.jpg,এসব কি? এটা কি?,1,1,4391
3,VizWiz_val_00000320.jpg,পর্দায় কি লেখা আছে?,1,1,1540
4,VizWiz_train_00013788.jpg,কে- মাইন,1,1,2152
...,...,...,...,...,...
1238,VizWiz_train_00003806.jpg,এই পৃষ্ঠা কী বলে?,2,0,3025
1239,VizWiz_train_00004115.jpg,এটা কিসের মডেল?,1,1,3719
1240,VizWiz_train_00004547.jpg,এই খাবারের নাম কি?,1,1,2545
1241,VizWiz_train_00019406.jpg,এই বাক্সে কি আছে?,2,0,349
1242,VizWiz_train_00010930.jpg,এটা কি বলে?,2,0,3025

In [46]:
embedding_size = encodings[0].shape[1] #change by Arif old was 768
classes = len(np.unique(ans_lb.classes_))
aux_classes = len(np.unique(train['answer_type']))
BATCH_SIZE = 64

In [53]:
encodings[0].shape[1]

1536

In [54]:
encd=torch.load('model-ml.pt')
class dataset(Dataset):
    def __init__(self, indices, answers, types, length):
        self.indices = indices
        self.answers = answers
        self.types = types
        self.length = length

    def __getitem__(self, index):
            if self.length <= 24842:
                return encd[self.indices[index]].float() , torch.tensor(int(self.answers[index])), torch.tensor(int(self.types[index]))
            
            return encd[self.indices[index]].float() , torch.tensor(int(self.answers[index % (self.length/2)])), torch.tensor(int(self.types[index % (self.length/2)]))
            
    def __len__(self):
          return self.length

/tmp/ipykernel_2294317/1329949184.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  encd=torch.load('model-ml.pt')

In [55]:

#trainDataset = dataset(np.concatenate((train_indices, train_indices_aug)), train['answer'], train['answer_type'], len(train_indices)*2)
trainDataset = dataset(np.array(range(train_indices.size)), train['answer'] , train['answer_type'], len(train_indices))

valDataset = dataset(np.array(range(test_indices.size)), test['answer'], test['answer_type'], len(test_indices))

#valDataset = dataset(np.array(list(range(encd.shape[0] - 5642, encd.shape[0]))), val['answer'], val['answer_type'], 4319)
#valDataset = dataset(np.array(list(range(encd.shape[0] - 5642, encd.shape[0]))), pd.DataFrame(e).iloc[24842:], val['answer_type'], 5642)

train_dataloader = DataLoader(trainDataset, batch_size = BATCH_SIZE, shuffle = True, num_workers=0)

val_dataloader = DataLoader(valDataset, batch_size = BATCH_SIZE, shuffle = True, num_workers=0)

In [56]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.ln1 = nn.LayerNorm(embedding_size*2)
        self.dp1 = nn.Dropout(0.5)
        self.fc1 = nn.Linear(embedding_size* 2, 512)
        
        self.ln2 = torch.nn.LayerNorm(512)
        self.dp2 = torch.nn.Dropout(0.5)
        
        self.fc2 = torch.nn.Linear(512, classes)
        
        self.fc_aux = torch.nn.Linear(512, aux_classes)
        
        self.lnaux = torch.nn.LayerNorm(aux_classes)
        self.dpaux = torch.nn.Dropout(0.5)
                
        self.fc_gate = torch.nn.Linear(aux_classes, classes)
        self.act_gate = torch.nn.Sigmoid()

    def forward(self, x):
        x = self.ln1(x)
        x = self.dp1(x)
        
        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        
        x = self.ln2(x)
        x = self.dp2(x)
        
#         aux
        aux = self.fc_aux(x)
#         aux = self.lnaux(aux)
#         aux = self.dpaux(aux)
        
#         linear bottom
        vqa = self.fc2(x)
        
        output = vqa * self.act_gate(self.fc_gate(aux))
        
        
        return output,aux

In [57]:
def run_model(model,dataloader,val_loader, optimizer,train = True ):
    if train:
        model.train()
    
    loss = nn.CrossEntropyLoss()
    
    total_loss = 0
    total_correct = 0
    total_samples = 0
    
    total_correct_ty = 0
    total_samples_ty = 0
    
    for (data, ans , ans_type) in tqdm(dataloader):
        data = data.to(device)
        ans = ans.to(device)
        ans_type = ans_type.to(device)
        optimizer.zero_grad()
        output , aux = model(data)
        
        loss_ans = loss(output, ans)
        loss_type = loss(aux,ans_type)
        loss_combined=loss_ans+loss_type
        total_loss += loss_combined.item()
        loss_combined.backward()
        optimizer.step()
        
        
#         Answer Accurracy
        _, predicted_labels = torch.max(output, dim=1)
        correct = (predicted_labels == ans).sum().item()
        total_correct += correct
        total_samples += ans.size(0)
        train_accuracy = total_correct / total_samples
        
#         Type Accuracy
        _, predicted_labels_ty = torch.max(aux, dim=1)
        correct_ty = (predicted_labels_ty == ans_type).sum().item()
        total_correct_ty += correct_ty
        total_samples_ty += ans_type.size(0)
        train_accuracy_ty = total_correct_ty / total_samples_ty
    
    total_train_accuracy = (train_accuracy + train_accuracy_ty) / 2
        
        
    if val_loader is not None:
        model.eval()

    # Initialize validation-specific variables
    val_loss = 0.0
    total_correct_val=0
    total_samples_val=0
    
    total_correct_val_ty=0
    total_samples_val_ty=0
    
    # Disable gradient calculation
    with torch.no_grad():
        # Iterate over the validation data
        for (data, ans , ans_type) in val_loader:
            data = data.to(device)
            ans = ans.to(device)
            ans_type = ans_type.to(device)
            
            # Forward pass
            output , aux = model(data)

            # Compute the loss
            loss_ans = loss(output, ans)
            loss_type = loss(aux,ans_type)
            loss_combined=loss_ans+loss_type
            val_loss += loss_combined.item()

            # Update validation metrics
            _, val_predicted = torch.max(output, dim=1)
            correct_val = (val_predicted == ans).sum().item()
            total_correct_val += correct_val
            total_samples_val += ans.size(0)
            val_accuracy = total_correct_val / total_samples_val
            
            _, val_predicted_ty = torch.max(aux, dim=1)
            correct_val_ty = (val_predicted_ty == ans_type).sum().item()
            total_correct_val_ty += correct_val_ty
            total_samples_val_ty += ans_type.size(0)
            val_accuracy_ty = total_correct_val_ty / total_samples_val_ty
        
        total_val_accuracy = (val_accuracy + val_accuracy_ty) / 2
        
    train_loss = total_loss/len(dataloader)
    val_loss = val_loss/len(val_loader)
    
    print(f"\nTrain Loss: {train_loss:.4f} | AVG Train ACC: {total_train_accuracy * 100:.4f}% | Val Loss: {val_loss:.4f} | AVG Val ACC: {total_val_accuracy * 100:.2f}%")
    
    print(f"\nTrain ANS ACC: {train_accuracy * 100:.4f}% | VAL ANS ACC: {val_accuracy * 100:.4f}% | Train TYPE ACC: {train_accuracy_ty * 100:.4f}% | VAL TYPE ACC: {val_accuracy_ty * 100:.2f}%\n")
        
    return train_loss, val_loss

In [58]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = Model()
model = model.to(device)
model = nn.DataParallel(model)

epoch = 125
training_loss = []
val_loss = []

optimizer = torch.optim.Adam(model.parameters(),1e-3)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, factor=.1, threshold=1e-6)

early_stopping_patience = 15  # Number of epochs to wait for improvement
best_val_loss = float('inf')
epochs_without_improvement = 0

for e in range(epoch):
    print(f'Epoch: {e+1}', f'| LR: { optimizer.param_groups[0]["lr"] }')
    trLoss, vlLoss = run_model(model,train_dataloader,val_dataloader,optimizer)    
    training_loss.append(trLoss)
    val_loss.append(vlLoss)
    
    scheduler.step(vlLoss)
    
    # Check if validation loss has improved
    if vlLoss < best_val_loss:
        best_val_loss = vlLoss
        epochs_without_improvement = 0
    else:
        epochs_without_improvement += 1

    # Check if early stopping criteria met
    if epochs_without_improvement >= early_stopping_patience:
        print(f"\nValidation loss hasn't improved for {early_stopping_patience} epochs. Early stopping.")
        break

Epoch: 1 | LR: 0.001

  0%|                                                                                                                                                                                                                           | 0/369 [00:00<?, ?it/s]

RuntimeError: Given normalized_shape=[3072], expected input with shape [*, 3072], but got input of size[64, 1, 1536]